{{- if .Values.dns_validation }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: devops@dozuki.com
    privateKeySecretRef:
      name: cert-issuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector:
          dnsZones:
            - "dozuki.guide"
            - "dozuki.cloud"
            - "dozuki.app"
        dns01:
          route53:
            region: us-east-1
            role: arn:aws:iam::010601635461:role/Route53AccessRole
{{- else }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: devops@dozuki.com
    privateKeySecretRef:
      name: cert-issuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            class: nginx
{{- end }}
