{{- range .Values.hpas }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}
spec:
  {{- if .behavior }}
  behavior:
    {{- if .behavior.scaleUp }}
    scaleUp:
      stabilizationWindowSeconds: {{ .behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        {{- range .behavior.scaleUp.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
    {{- end }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .scaleTargetRef.name }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- range .metrics }}
    - type: {{ .type }}
      resource:
        name: {{ .resource.name }}
        target:
          type: {{ .resource.target.type }}
          averageUtilization: {{ .resource.target.averageUtilization }}
    {{- end }}
---
{{- end }}
