{{- range .Values.secrets }}
  {{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
{{- if .data }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
{{- if .stringData }}
stringData:
  {{- range $key, $value := .stringData }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
  {{- end }}
---
{{- end }}