apiVersion: v1
kind: ConfigMap
metadata:
  name: dozuki-resources-configmap
data:
  memcached.json: |
    {
      "localCluster": {
        "servers": [
          {
            "hostname": "{{ .Values.memcached.host }}",
            "port": 11211
          }
        ]
      },
      "globalCluster": {
        "servers": [
          {
            "hostname": "{{ .Values.memcached.host }}",
            "port": 11211
          }
        ]
      },
      "testCluster": {
        "servers": [
          {
            "hostname": "{{ .Values.memcached.host }}",
            "port": 11211
          }
        ]
      }
    }
  aws-resources.json: |
    {
      "S3.enabled": true,
      "Ec2.enabled": true,
      "CloudFront.enabled": false,
      "LH.localFileSystem": false,
      "CdnUrls.alwaysRelative": false
    }
  s3.json: |
    {
      "region": "{{ .Values.aws.region }}",
      "encryptionKeyId": "{{ .Values.s3.kmsKey }}"
      {{- if .Values.minio.enabled }}
      ,"endpoint": "http://dozuki-minio.{{ .Release.Namespace }}.svc.cluster.local"
      {{- end }}
    }
  buckets.json: |
    {
      "default": {
        "guide-images": "{{ .Values.s3.imagesBucket }}",
        "guide-pdfs": "{{ .Values.s3.pdfsBucket }}",
        "documents": "{{ .Values.s3.documentsBucket }}",
        "guide-objects": "{{ .Values.s3.objectsBucket }}"
      }
    }
  common.json: |
    {
      "baseNanositeDomain": "{{ .Values.hostname }}"
    }
  db.json: |
    {
      "generic": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}"
      },
      "master": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}"
      },
      "slave": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}"
      },
      "sphinx": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}"
      }
    }
  surveyjs.json: |
    {
      "licenseKey": "{{ .Values.surveyjs.licenseKey }}"
    }
  google-translate.json: |
    {
      "apiToken": "{{ .Values.googleTranslate.token }}"
    }
  index.json: |
    {
      "index": {
        "legacy": {
          "filename": "legacy.json"
        },
        "s3": {
          "filename": "s3.json"
        },
        "buckets": {
          "filename": "buckets.json"
        },
        "db": {
          "filename": "db.json"
        },
        "memcached": {
          "filename": "memcached.json"
        },
        "aws-resources": {
          "filename": "aws-resources.json"
        }
      }
    }
  saml.json: |
    {
      "activeX509CertPath": "/var/www/key/tls.crt",
      "activePrivateKeyPath": "/var/www/key/tls.key",
      "pendingX509CertPath": "/var/www/key/tls.crt",
      "signatureAlgorithm": "RSA_SHA256"
    }
